export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8081'
export const POLLING_MS = import.meta.env.VITE_POLLING_INTERVAL_MS || 25000

export const ROLES = { USER: 'USER', ADMIN: 'ADMIN', TECHNICIAN: 'TECHNICIAN' }
export const BOOKING_STATUSES = ['PENDING', 'APPROVED', 'REJECTED', 'CANCELLED']
export const TICKET_STATUSES = ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED']
export const TICKET_PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']

// Resource Types (Frontend)
export const RESOURCE_TYPES = {
  STUDY_ROOM: 'STUDY_ROOM',
  AUDITORIUM: 'AUDITORIUM',
  CAMERA: 'CAMERA',
  LECTURE_HALL: 'LECTURE_HALL',
  LIBRARY: 'LIBRARY',
  PROJECTOR: 'PROJECTOR',
  LAB: 'LAB',
  OTHER_EQUIPMENT: 'OTHER_EQUIPMENT',
  SPORTS_FACILITY: 'SPORTS_FACILITY',
  MEETING_ROOM: 'MEETING_ROOM'
}

// Resource Statuses (Frontend)
export const RESOURCE_STATUSES = {
  ACTIVE: 'ACTIVE',
  OUT_OF_SERVICE: 'OUT_OF_SERVICE'
}

// API Resource Statuses (Backend)
export const API_RESOURCE_STATUSES = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  MAINTENANCE: 'MAINTENANCE',
  BLOCKED: 'BLOCKED'
}
